import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import "./globals.css";
import Providers from "@/app/[locale]/Providers";
import { Nav } from "@/components/layout/Nav";
import { hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from "@/i18n/routing";
import { } from "../../messages/en"
type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

//   const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
//   });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children, params
}: Props) {
  const { locale } = await params;
  const messages = (await import(`../../messages/${locale}`)).default;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
    return (<></>)
  }
  return (
    <html
      lang={locale} dir={locale === 'fa' ? 'rtl' : 'ltr'}
      suppressHydrationWarning
      className={`${poppins.className} h-full antialiased`}
    >

      <body className="min-h-full flex flex-col" >

        <Providers locale={locale} messages={messages}>

          <Toaster />
          <Nav />
          {children}
        </Providers>
      </body>

    </html>)

}
